### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Anghellos** [joaorb64/joycond-cemuhook#21]
Hello,

i followed the instructions to install the joycond-cemuhood on my laptop (running Ubuntu 20.10).
when i run the following command "python3 joycond-cemuhook.py" i received this error:
_Traceback (most recent call last):
  File "joycond-cemuhook.py", line 632, in <module>
    server = UDPServer(ip, port)
  File "joycond-cemuhook.py", line 269, in __init__
    self.sock.bind((host, port))
OSError: [Errno 98] Address already in use_

can you help me please to resolve it?

**Comment by joaorb64** [comment]
Unless you have something else running on port 26760, I think a restart might solve it. Other than that, try running with `python3 joycond-cemuhook.py -p 26761` (or any other port) and see if it works.
