### ISSUE TITLE
Unable to connect my pro controller today

### ISSUE THREAD

**Issue by dracula99gr** [joaorb64/joycond-cemuhook#66]
This is my terminal output. It worked like a charm yesterday and some days prior to this!

efi@efi-hppaviliong6notebookpc:~$ python3 ~/joycond-cemuhook/joycond-cemuhook.py
Looking for Nintendo Switch controllers...
Traceback (most recent call last):
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 798, in <module>
    main()
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 794, in main
    handle_devices(stop_event)
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 731, in handle_devices
    add_devices(device, motion_devices)
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 609, in add_devices
    added = server.add_devices(device, motion_devices, motion_only)
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 523, in add_devices
    if self.add_device(device, motion_device, motion_only if i == 0 else True) == UDPServer.MAX_PADS:
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 512, in add_device
    self.slots[i] = SwitchDevice(self, i, device, motion_device, motion_only)
  File "/home/efi/joycond-cemuhook/joycond-cemuhook.py", line 144, in __init__
    with open(os.path.join('profiles', self.name + '.json')) as profile:
FileNotFoundError: [Errno 2] No such file or directory: 'profiles/Nintendo Switch Pro Controller.json'

**Comment by Romroig** [comment]
The error message "FileNotFoundError: [Errno 2] No such file or directory: 'profiles/Nintendo Switch Pro Controller.json'" suggests that joycond-cemuhook.py is unable to locate the profile for your Nintendo Switch Pro Controller. Here are a few steps you can try to resolve the issue:

1-Check if the profile file is still present in the expected location: ‘**~/joycond-cemuhook/profiles/Nintendo Switch Pro Controller.json**’. If it has been deleted or moved, try restoring it or updating the joycond-cemuhook configuration to point to the new location of the profile file.

2-Verify that your Nintendo Switch Pro Controller is properly connected to your system and that it is recognized as a controller. You can check this by running the ’**jstest-gtk**’ command in your terminal and verifying that your controller is listed and functioning properly.

3-Restart joycond-cemuhook by running the ’**sudo systemctl restart joycond-cemuhook**’ command in your terminal. This will restart the joycond-cemuhook service and may help resolve any issues that were preventing your controller from being detected.
