### ISSUE TITLE
gi module issue while running joycond-cemuhook

### ISSUE THREAD

**Issue by Sailinnov** [joaorb64/joycond-cemuhook#98]
My env is:
Ubuntu 24.04
python 3.12.5

when I tried to run joycond-cemuhook, I got the error shown below:

$ joycond-cemuhook
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/joycond-cemuhook", line 5, in <module>
    from joycond_cemuhook import main
  File "/home/username/anaconda3/lib/python3.12/site-packages/joycond_cemuhook/__init__.py", line 19, in <module>
    from gi.repository import GLib
  File "/home/username/anaconda3/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: undefined symbol: g_once_init_leave_pointer

I think the dependencies are installed with latest version, maybe a compatibility issue of my system env

**Comment by AteebXYZ** [comment]
i have the same issue on fedora 41 with python3.13

**Comment by AteebXYZ** [comment]
Ok i managed to fix my issue by doing this:
pip3 uninstall PyGObject-stubs

Then i just installed joycond-cemuhook like this:
pip3 install git+https://github.com/joaorb64/joycond-cemuhook

Then PyGObject installed correctly and there were no errors.
Hope this helps.

**Comment by Ludo2000** [comment]
I have a similar issue with Ubuntu 24.10:

$ joycond-cemuhook
Traceback (most recent call last):
  File "/home/ludo/.local/bin/joycond-cemuhook", line 5, in <module>
    from joycond_cemuhook import main
  File "/home/ludo/.local/share/pipx/venvs/joycond-cemuhook/lib/python3.12/site-packages/joycond_cemuhook/__init__.py", line 19, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'


In my system the python3-gi package is installed with apt.
If I run python by command line I can impor GLib:

$ python3
Python 3.12.7 (main, Nov  6 2024, 18:29:01) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from  gi.repository import GLib
>>> 

Thanks in advance.

**Comment by CallMeNP** [comment]
I also encountered this issue at first, the gi module could not be found. 

Later, I manually installed `PyGObject` and it worked fine.

I am using a venv environment to install this tool `joycond-cemuhook`. To be precise, it's `pipx`. For `pipx`, you need to execute these commands:

```bash
pipx install git+https://github.com/joaorb64/joycond-cemuhook
pipx inject joycond-cemuhook PyGObject
```

After that, when I actually ran it, I encountered an error. 

```
future: <Task finished name='Task-2559' coro=<SwitchDevice._handle_events() done, defined at /home/np/.local/share/pipx/venvs/joycond-cemuhook/lib/python3.12/site-packages/joycond_cemuhook/__init__.py:277> exception=ValueError('Invalid file descriptor: -1')>
Traceback (most recent call last):
  File "/home/np/.local/share/pipx/venvs/joycond-cemuhook/lib/python3.12/site-packages/evdev/eventio_async.py", line 42, in __anext__
    future.set_result(next(self.current_batch))
                      ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/np/.local/share/pipx/venvs/joycond-cemuhook/lib/python3.12/site-packages/joycond_cemuhook/__init__.py", line 280, in _handle_events
......
......
```
When I downgraded the Python version from 3.12 to 3.9, everything worked fine.
